"""
Analyze InternVLA-M1 rollout embeddings for command variation overlap.

Metrics per task (default vs l1/l2/l3):
- Cosine similarity
- Euclidean distance (L2)
- Normalized Levenshtein distance

Input format is the pickle generated by:
extract_text_embeddings_rollout_internvla.py
"""

import argparse
import glob
import os
import pickle
from typing import Dict, Iterable, List, Optional

import numpy as np
import pandas as pd


def _levenshtein_fallback(text1: str, text2: str) -> int:
    if text1 == text2:
        return 0
    if len(text1) == 0:
        return len(text2)
    if len(text2) == 0:
        return len(text1)

    prev = list(range(len(text2) + 1))
    for i, c1 in enumerate(text1, start=1):
        curr = [i]
        for j, c2 in enumerate(text2, start=1):
            ins = curr[j - 1] + 1
            delete = prev[j] + 1
            sub = prev[j - 1] + (0 if c1 == c2 else 1)
            curr.append(min(ins, delete, sub))
        prev = curr
    return prev[-1]


try:
    from Levenshtein import distance as _levenshtein_distance
except Exception:
    _levenshtein_distance = _levenshtein_fallback


def cosine_similarity_np(vec1: np.ndarray, vec2: np.ndarray) -> float:
    v1 = np.asarray(vec1, dtype=np.float64).reshape(-1)
    v2 = np.asarray(vec2, dtype=np.float64).reshape(-1)
    denom = (np.linalg.norm(v1) * np.linalg.norm(v2))
    if denom == 0.0:
        return 0.0
    return float(np.dot(v1, v2) / denom)


def euclidean_distance_np(vec1: np.ndarray, vec2: np.ndarray) -> float:
    v1 = np.asarray(vec1, dtype=np.float64).reshape(-1)
    v2 = np.asarray(vec2, dtype=np.float64).reshape(-1)
    return float(np.linalg.norm(v1 - v2, ord=2))


def compute_levenshtein_normalized(text1: str, text2: str) -> float:
    text1 = text1 or ""
    text2 = text2 or ""
    max_len = max(len(text1), len(text2))
    if max_len == 0:
        return 0.0
    return float(_levenshtein_distance(text1, text2) / max_len)


def load_embeddings(
    embedding_file: Optional[str] = None,
    embedding_files: Optional[Iterable[str]] = None,
    embedding_dir: Optional[str] = None,
) -> Dict:
    if embedding_file:
        files = [embedding_file]
    elif embedding_files:
        files = list(embedding_files)
    elif embedding_dir:
        files = sorted(glob.glob(os.path.join(embedding_dir, "*.pkl")))
    else:
        raise ValueError("Provide one between embedding_file, embedding_files, or embedding_dir.")

    if not files:
        raise FileNotFoundError("No embedding pickle files found.")

    all_embeddings = {}
    print(f"Loading {len(files)} pickle file(s)...")
    for filepath in files:
        print(f"  - {filepath}")
        with open(filepath, "rb") as f:
            data = pickle.load(f)
            if not isinstance(data, dict):
                raise ValueError(f"Unexpected pickle format in {filepath}: expected dict")
            all_embeddings.update(data)

    print(f"Total embedding entries: {len(all_embeddings)}")
    return all_embeddings


def analyze_embeddings(embeddings: Dict, output_csv: str) -> pd.DataFrame:
    tasks = {}
    for _, item in embeddings.items():
        task_id = item.get("task_id")
        level = item.get("command_level")
        if task_id is None or level is None:
            continue
        tasks.setdefault(task_id, {})[level] = item

    rows: List[Dict] = []

    print("\n" + "=" * 90)
    print("DISTANCE ANALYSIS (INTERNVLA-M1)")
    print("default vs l1/l2/l3 on text-backbone embeddings")
    print("=" * 90)

    for task_id in sorted(tasks.keys()):
        task_levels = tasks[task_id]
        if "default" not in task_levels:
            continue

        default_item = task_levels["default"]
        default_emb = np.asarray(default_item["embedding"]).reshape(-1)
        default_cmd = default_item.get("command_text", "")

        print(f"\nTask {task_id:02d}")
        print(f"  default: {default_cmd}")

        for level in ("l1", "l2", "l3"):
            if level not in task_levels:
                print(f"  {level}: [missing]")
                continue

            var_item = task_levels[level]
            var_emb = np.asarray(var_item["embedding"]).reshape(-1)
            var_cmd = var_item.get("command_text", "")

            cos = cosine_similarity_np(default_emb, var_emb)
            euc = euclidean_distance_np(default_emb, var_emb)
            lev = compute_levenshtein_normalized(default_cmd, var_cmd)

            rows.append(
                {
                    "task_id": task_id,
                    "task_name": default_item.get("task_name"),
                    "level": level,
                    "default_command": default_cmd,
                    "variation_command": var_cmd,
                    "default_rollouts": default_item.get("num_rollouts"),
                    "variation_rollouts": var_item.get("num_rollouts"),
                    "default_success_rate": default_item.get("success_rate"),
                    "variation_success_rate": var_item.get("success_rate"),
                    "cosine_similarity": cos,
                    "euclidean_distance": euc,
                    "levenshtein_distance": lev,
                }
            )

            print(f"  {level}: {var_cmd}")
            print(f"      cosine={cos:.4f} | euclidean={euc:.4f} | levenshtein={lev:.4f}")

    df = pd.DataFrame(rows)
    if df.empty:
        raise RuntimeError("No comparable pairs found. Check embeddings and command levels.")

    print("\n" + "=" * 90)
    print("AVERAGE BY LEVEL")
    print("=" * 90)
    for level in ("l1", "l2", "l3"):
        part = df[df["level"] == level]
        if part.empty:
            continue
        print(
            f"{level.upper()}: cosine={part['cosine_similarity'].mean():.4f} +/- {part['cosine_similarity'].std():.4f} | "
            f"euclidean={part['euclidean_distance'].mean():.4f} +/- {part['euclidean_distance'].std():.4f} | "
            f"levenshtein={part['levenshtein_distance'].mean():.4f} +/- {part['levenshtein_distance'].std():.4f}"
        )

    print("\nOVERALL:")
    print(
        f"  cosine={df['cosine_similarity'].mean():.4f} +/- {df['cosine_similarity'].std():.4f} | "
        f"euclidean={df['euclidean_distance'].mean():.4f} +/- {df['euclidean_distance'].std():.4f} | "
        f"levenshtein={df['levenshtein_distance'].mean():.4f} +/- {df['levenshtein_distance'].std():.4f}"
    )

    os.makedirs(os.path.dirname(output_csv) or ".", exist_ok=True)
    df.to_csv(output_csv, index=False)
    print(f"\nSaved CSV: {output_csv}")

    base = output_csv.rsplit(".", 1)[0]
    for level in ("l1", "l2", "l3"):
        part = df[df["level"] == level].reset_index(drop=True)
        if part.empty:
            continue
        out_xlsx = f"{base}_overlap_{level}.xlsx"
        _save_formatted_overlap_table(part, level, out_xlsx)

    return df


def _save_formatted_overlap_table(level_df: pd.DataFrame, level: str, output_path: str) -> None:
    try:
        import openpyxl
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        from openpyxl.utils import get_column_letter
    except Exception:
        print("openpyxl not available, skipping formatted xlsx table export.")
        return

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = f"{level.upper()} Variations"

    ws.merge_cells("A1:F1")
    ws["A1"].value = f"Overlap Analysis - {level.upper()} Variations"
    ws["A1"].font = Font(bold=True, size=13)
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")

    headers = [
        "N",
        "Original Task Command",
        "Variation Task Command",
        "Cosine Similarity",
        "Euclidean Dist.",
        "Levenshtein Dist.",
    ]

    header_fill = PatternFill(fill_type="solid", fgColor="2F5496")
    header_font = Font(bold=True, color="FFFFFF")
    thin = Side(style="thin", color="000000")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for col, text in enumerate(headers, start=1):
        cell = ws.cell(row=2, column=col, value=text)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border

    alt_fill = PatternFill(fill_type="solid", fgColor="DCE6F1")

    for idx, row in level_df.iterrows():
        excel_row = idx + 3
        fill = alt_fill if idx % 2 == 1 else None
        values = [
            idx + 1,
            row["default_command"],
            row["variation_command"],
            round(float(row["cosine_similarity"]), 4),
            round(float(row["euclidean_distance"]), 4),
            round(float(row["levenshtein_distance"]), 4),
        ]

        for col, val in enumerate(values, start=1):
            cell = ws.cell(row=excel_row, column=col, value=val)
            cell.border = border
            cell.alignment = Alignment(vertical="center", wrap_text=True)
            if fill is not None:
                cell.fill = fill
            if col >= 4:
                cell.number_format = "0.0000"
                cell.alignment = Alignment(horizontal="center", vertical="center")

    avg_row = len(level_df) + 3
    avg_fill = PatternFill(fill_type="solid", fgColor="F4B942")
    avg_font = Font(bold=True)

    def fmt(col):
        return f"{level_df[col].mean():.4f} +/- {level_df[col].std():.4f}"

    avg_values = [
        "AVERAGE",
        "",
        "",
        fmt("cosine_similarity"),
        fmt("euclidean_distance"),
        fmt("levenshtein_distance"),
    ]
    for col, val in enumerate(avg_values, start=1):
        cell = ws.cell(row=avg_row, column=col, value=val)
        cell.font = avg_font
        cell.fill = avg_fill
        cell.border = border
        cell.alignment = Alignment(horizontal="center", vertical="center")

    col_widths = [6, 52, 52, 18, 16, 18]
    for col, width in enumerate(col_widths, start=1):
        ws.column_dimensions[get_column_letter(col)].width = width

    wb.save(output_path)
    print(f"Saved formatted table: {output_path}")


def compare_per_rollout_similarity(embeddings: Dict, task_id: int, level: str):
    default_key = f"task_{task_id:02d}_default"
    var_key = f"task_{task_id:02d}_{level}"

    if default_key not in embeddings or var_key not in embeddings:
        print(f"Missing keys: {default_key} or {var_key}")
        return None

    d = embeddings[default_key]
    v = embeddings[var_key]

    if "embedding_per_rollout" not in d or "embedding_per_rollout" not in v:
        print("Per-rollout embeddings not available in selected entries.")
        return None

    d_roll = np.asarray(d["embedding_per_rollout"])
    v_roll = np.asarray(v["embedding_per_rollout"])
    n = min(len(d_roll), len(v_roll))

    cos_vals = []
    euc_vals = []
    for i in range(n):
        cos_vals.append(cosine_similarity_np(d_roll[i], v_roll[i]))
        euc_vals.append(euclidean_distance_np(d_roll[i], v_roll[i]))

    cos_vals = np.asarray(cos_vals)
    euc_vals = np.asarray(euc_vals)

    print(f"\nPer-rollout analysis task={task_id}, level={level}, n={n}")
    print(f"  cosine mean/std/min/max: {cos_vals.mean():.4f} / {cos_vals.std():.4f} / {cos_vals.min():.4f} / {cos_vals.max():.4f}")
    print(f"  euclid mean/std/min/max: {euc_vals.mean():.4f} / {euc_vals.std():.4f} / {euc_vals.min():.4f} / {euc_vals.max():.4f}")

    return cos_vals, euc_vals


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze InternVLA rollout embedding overlap")
    parser.add_argument("--embedding_file", type=str, default=None)
    parser.add_argument("--embedding_files", type=str, nargs="+", default=None)
    parser.add_argument("--embedding_dir", type=str, default=None)
    parser.add_argument("--output_csv", type=str, default=None)
    parser.add_argument("--per_rollout_analysis", action="store_true")
    parser.add_argument("--task_id", type=int, default=0)
    parser.add_argument("--level", type=str, default="l1")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    embeddings = load_embeddings(
        embedding_file=args.embedding_file,
        embedding_files=args.embedding_files,
        embedding_dir=args.embedding_dir,
    )

    if args.output_csv:
        output_csv = args.output_csv
    else:
        if args.embedding_file:
            base = os.path.splitext(args.embedding_file)[0]
        elif args.embedding_dir:
            base = os.path.join(args.embedding_dir, "internvla_combined_analysis")
        else:
            base = os.path.join(os.path.dirname(args.embedding_files[0]), "internvla_combined_analysis")
        output_csv = f"{base}.csv"

    analyze_embeddings(embeddings, output_csv=output_csv)

    if args.per_rollout_analysis:
        compare_per_rollout_similarity(embeddings, task_id=args.task_id, level=args.level.lower())
